version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  auth-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Jestinod98661
      MYSQL_DATABASE: auth
    ports:
      - "3306:3306"

  student-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: jestinod98661
      MYSQL_DATABASE: student
    ports:
      - "3307:3306"

  teacher-db:
      image: mysql:latest
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: teacher_db
      ports:
        - "3308:3306"

  course-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: course_db
    ports:
      - "3309:3306"