
server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0
        - id: student-service
          uri: http://localhost:8082
          predicates:
            - Path=/students/**
          filters:
            - StripPrefix=0
        - id: teacher-service
          uri: http://localhost:8083
          predicates:
            - Path=/teachers/**
          filters:
            - StripPrefix=0
        - id: course-service
          uri: http://localhost:8084
          predicates:
            - Path=/courses/**
          filters:
            - StripPrefix=0
jwt:
  secret: your-very-secure-secret-key
