
server:
  port: 8085
spring:
  application:
    name: course-service
  datasource:
    url: jdbc:mysql://localhost:3306/course_db
    username: root
    password: Jestinod98661
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: course-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
jwt:
  secret: your-very-secure-secret-key