#spring.application.name=student-service
server:
  port: 8083
spring:
  application:
    name: student-service
  datasource:
    url: jdbc:mysql://localhost:3306/student
    username: root
    password: Jestinod98661
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

kafka:
  bootstrap-servers: localhost:9092
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer

jwt:
  secret: 12335thyjkugfdresbhnjuytdgjgjjkgjk
  expiration: 86400000